### PR TITLE
Handle nosidebar

### PR DESCRIPTION
**Pull request by silverailscolo**
Load order change

### CODE REVIEW

**Comment by silverailscolo** [comment]
@bobjacobsen thanks for quick merge. Now works as planned on iOS an Mac. See example [Help TOC](https://www.jmri.org/help/en/webtoc.shtml)

**Comment by danielb987** [comment]
@silverailscolo 
Have you tested on Windows? If not, do you want me to test? I have Firefox and Brave (Chromium) on Windows 8.1. If so, what do you want me to test?

**Comment by silverailscolo** [comment]
@danielb987 when you open the above link to TOC, can you confirm no "hamburger" menu shows on the top left? (it might flash shortly at load).

**Comment by danielb987** [comment]
There is a difference between [Help TOC](https://www.jmri.org/help/en/webtoc.shtml) and [Applications](https://www.jmri.org/help/en/html/apps/index.shtml). The former has a white horizontal space at the top of the page. On the Applications page, the gray field with releases, applications, hardware, ..., are directly below the address bar. On the Help TOC page, there is a white space in between.

---

**Help TOC**
TOC

---

**Applications**
Applications

**Comment by danielb987** [comment]
I now notice that as soon as I scroll the Help TOC page, the white space disappears. But every time I open the page it's there. But if I scroll, the white space disappears.

**Comment by danielb987** [comment]
The white space is no big problem, but I noticed it.

**Comment by silverailscolo** [comment]
Thanks. We have only partial control over the TOC pages as they are autogenerated, which might explain this.

**Pull request merged**
