### PR TITLE
Website Help responsive

### PR DESCRIPTION
**Pull request by silverailscolo**
CSS based update of jmri.org to improve access on different display sizes. Sliding sidebar, more compact menu, fixed at the top of screen.
Fresh colors, kept the purple. Initially set up to only create a couple of demo pages.
Includes documentation for tags to use, and migration prep and day 0 tasks.

### CODE REVIEW

**Comment by jerryg2003** [comment]
If I understand correctly what you have done,  we can try this out by viewing jmri.org/index2020.shtml and can slowly migrate (for a while at least) by creating some more index2020 pages that reference Header2020 and Sidebar2020 (I didn’t see a Footer2020).  I like the ability to do a slow migration before a complete switchover - too many page variations, too many browser variations to test beforehand.  Am I correct?  Feel free to contact me via email.  Thanks, Jerry

**Comment by danielb987** [comment]
This PR has now a conflict with master with the file `Footer.shtml`.

**Comment by silverailscolo** [comment]
@jerryg2003 Tonight I worked through most of the website shtml pages to add the script and Style include. I want to migrate all install pages to shtml, despite the link. Many are pretty rare and if they're missed the index update will bring it up. The use of includes and thus shtml is vital for efficient maintenance.
In PR the new css and header are swapped with the current once, those now renamed ...2020.
Will clean up de .website Sidebars in a separate PR (mixed dl-dt-h4 is not valid html for a reason).
No review of actual content.

**Comment by jerryg2003** [comment]
Sounds like great progress (and a lot of work!).  Happy to help by doing some testing.  Is there a way for you to generate a Windows version of an installable file I can download somewhere?  Unfortunately, I do not have a development environment nor the capability to generate installable versions on my own.  Thanks.

**Review by jerryg2003 — COMMENTED** [review]
Sidebar.shtml has been updated since you did this.  Please make sure you are not overwriting new updates.

**Comment by jerryg2003** [comment]
As I look over a few more files (not all 405!), I have a basic question:  I thought what you were doing was creating a 
Sidebar2021 and css2021 that would embody the new responsive UX.  This would allow us to migrate help/web system files over time, putting references to those into help files on a topic-by-topic basis, leaving some topics with the existing Sidebar and css with current behavior.  Is this incorrect?  Do we have to migrate everything all at once under your approach?

Thanks.

**Comment by silverailscolo** [comment]
@jerryg2003 we can choose either way but to save us some effort on day 1 I now set it up to replace the existing Sidebars, as well as Style and Header. Footer has no script, just reordering of the existing pieces.
This allows the whole site (starting with the `website` repo to get a new face overnight (with us getting some sleep) without the need to later touch and check every page, as I already had to add the main page `js` and html5 header. All done.
Either way, a bit of stress will always be involved in this migration, as you never see the scripts working together until all parts are running from the server.
We should plan for a suitable day for the switch, so that we have time to fix the spots that need a bit of extra tweaking. I'd prefer a Thursday night in 2-3 weeks over a weekend where our users will expect to have access to jmri.org

The follow up work will be more spread out, properly applying the new css for reflow and weed out the old style tags that just try to do positioning (mind all the `<p>` and `<h2>` tags inside `<li>`s, `<table>` and `<code>` blocks).

**Comment by danielb987** [comment]
Would it be a disaster if some pages didn't work well for some days or a week? I don't think so. I have experience of web sites and web forums going down and people survive that.

You might end up writing a message on the JMRI users list that some pages aren't working due to web site upgrade, and that you apoligize that some things doesn't work. Most users understand that and accept it.

If you want, you can write a message to the JMRI users list in advance telling that the web site is going thru a big change and that there might be problems accessing the web site for a week or so. It's easier for people to accept it if they understand why it happens. And sometimes big updates are absolutely necessary.

Good luck with the transition!

**Comment by bobjacobsen** [comment]
> I would certainly prefer doing testing before we unleash this on the whole population. But how can we test if “you never see the scripts working together until all parts are running from the server”?

When it's really hard to test something, then the balance of risk/reward goes toward "roll it out, check, and be prepared to roll it back".

One way to do that is to create the changes on a git branch and switch the web server to that branch.  Then it's a quick matter to switch back to the master content if needed.

**Comment by silverailscolo** [comment]
Migrating as a branch sounds like the route to go. Is there something I need to do on the PR far that? Create the branch on JMRI/website first, I expect.

**Comment by bobjacobsen** [comment]
The easiest way to set the web server to another branch is to, well, set the web server to that branch.  It's not about the PR (which is for a _permanent_ merge). It's just an identification of which branch and when.

For example, we could agree to switch to the `silverailscolo:eb-responsive` at some specific time. 

Is there another  corresponding branch for the JMRI/JMRI repository? If so, we should switch that part too.

**Comment by silverailscolo** [comment]
The complementing part is on `eb-responsive-JMRI`

**Comment by bobjacobsen** [comment]
OK.  So we can switch the server at any time you're ready.  Just give me a half-day advance notice.

It would be helpful, but not critical, to resolve the merge conflicts first.  You'll want to merge it at some point, and it would be good to test the mergeable content.

I recommend you discuss this in advance on jmri-developers and/or jmriusers so people know its coming.

**Comment by bobjacobsen** [comment]
Are we still going to switch the web server to a branch? That'll let people benefit from this work.

If so, it would be good to fix the conflicts and bring this up to the head of master first.

**Comment by silverailscolo** [comment]
I will try to fix the conflicts in a week. Egbert

**Comment by silverailscolo** [comment]
Done. Ready to go (by pointing een server to branch per @bobjacobsen planned)

**Comment by danielb987** [comment]
@silverailscolo 
Just a reminder that @bobjacobsen wrote above that:
> I recommend you discuss this in advance on jmri-developers and/or jmriusers so people know its coming.

**Comment by silverailscolo** [comment]
I have sent out a message describing the web update on both lists.

**Comment by bobjacobsen** [comment]
The JMRI webserver is now being loaded from this `silverailscolo:eb-responsive` branch.  That's just temporary, until things are merged to master.

Looks good!

**Comment by jerryg2003** [comment]
Is there/will there be a URL i can use to try this?  Thanks.

**Comment by danielb987** [comment]
> Is there/will there be a URL i can use to try this? Thanks.

https://www.jmri.org/

**Comment by dsand47** [comment]
> The JMRI webserver is now being loaded from this `silverailscolo:eb-responsive` branch. That's just temporary, until things are merged to master.
> 
> Looks good!

Is the website also using the eb-responsive-jmri branch for the JMRI/JMRI components?

Using both branches locally, there are recent changes that need to merged from the respective masters.

**Comment by silverailscolo** [comment]
Thanks for your trust and patience. I made some path fixes in this branch and pulled the changes from master.
@bobjacobsen will these be copied automatically to the host?

**Comment by bobjacobsen** [comment]
Any changes to this branch will (after a short wait) be automatically be pushed.

**Comment by dsand47** [comment]
There are a couple of minor fixes:
- default.css is missing a comma
- the download page needs the first line wrapped in the p tag.

```
diff --git a/css/default.css b/css/default.css
index 17e3f590..b8d29081 100755
--- a/css/default.css
+++ b/css/default.css
@@ -278,12 +278,12 @@
                border: solid #FFD700; /* --primary-color2 - Orange */
        }
 
-    p.noted
+    p.noted,
     div.noted {
                margin: 1em;
                padding: 0.1em;
                border: 2px solid #778899; /* --primary-color3: LightSlateGray */
-       }       
+       }
 
        span.important,
        em.important,
 
diff --git a/download/index.shtml b/download/index.shtml
index 339d0b9b..535e4ed9 100644
--- a/download/index.shtml
+++ b/download/index.shtml
@@ -18,7 +18,7 @@
  <hr class="hide">
  <div id="mainContent">
 
-    This page describes JMRI releases.  Briefly, we have three kinds:
+    <p>This page describes JMRI releases.  Briefly, we have three kinds:</p>
     <ul>
     <li>"<a href="#prod-rel">Production releases</a>" about twice a year.  These are the ones we recommend to general users.
     <li>"<a href="#test-rel">Test releases</a>", usually <a href="https://github.com/JMRI/JMRI/milestones?direction=asc&sort=due_date&state=open">about monthly</a>.
```

**Comment by jerryg2003** [comment]
I used the tag “””<p class=“noted””””> in several places and it had a nice box around the paragraph.  That box now seems to be missing.

**Comment by dsand47** [comment]
> I used the tag “””p class=“noted”””” in several places and it had a nice box around the paragraph. That box now seems to be missing.

The css class definition is missing a comma.  I mentioned that in the previous post.

**Comment by silverailscolo** [comment]
The box is back, Jerry! Also fixed pages that used an extra div of class Container.
For anyone interested, development notes are kept with the new page templates in https://www.jmri.org/templates/

**Comment by dsand47** [comment]
The home page sidebar has a processing error.

```
	    <!--#include virtual="./help/en/parts/SidebarToolsNew.shtml" -->

        <!--#include virtual="./help/en/parts/SidebarLayoutAutomationNew.shtml" -->

	    <!--#include virtual="./help/en/parts/SidebarSupportedHardwareNew.shtml" -->

	    <!--#include virtual="./help/en/parts/SidebarInstallNew.shtml" -->
```

`SidebarSupportedHardwareNew.shtml` does not exist.

These should probably no longer be using the **_new_** versions.

**Comment by silverailscolo** [comment]
> The home page sidebar has a processing error.
> 
> ```
> 	    
> 
>         
> 
> 	    
> 
> 	    
> ```
> 
> `SidebarSupportedHardwareNew.shtml` does not exist.
> 
> These should probably no longer be using the **_new_** versions.

I fixed this issue (for responsive site branch only) I hope by correcting the link to `SidebarSupportedHardware` that was in the `SidebarSupportedHardwareNew` include

**Comment by silverailscolo** [comment]
Off for the weekend, so I won't be able to add more fixes.
At the moment this branch (and the website conterpart) is mergeable against master.
Ready to merge, and share the fun?

**Pull request merged**
