### PR TITLE
Update main Sidebar

### PR DESCRIPTION
**Pull request by jerryg2003**
Add link to new Jython Apps page (implemented in JMRI/JMRI PR #9451

### CODE REVIEW

**Review by dsand47 — APPROVED** [review]
Looks good.

**Comment by danielb987** [comment]
@jerryg2003 Where do you find a page with this sidebar? I'm trying to find it, but fails.

This page is similar, but don't have the `Cool Uses` section:
https://www.jmri.org/help/en/html/apps/index.shtml

While you are at it, the `manuals` page look strange:
https://www.jmri.org/help/en/manual/index.shtml

I have the same issue both in Firefox and Brave (a Chrome based browser)
Manuals

**Comment by dsand47** [comment]
> @jerryg2003 Where do you find a page with this sidebar? I'm trying to find it, but fails.
> 

The sidebar is on the main page.
Screen Shot 2021-02-26 at 2 01 30 PM

However, there is a timing issue.  The new link points to the help tree which has not been updated yet.  Those changes are in PR #9451.

I think the risk of someone using the new link is very small.

**Comment by jerryg2003** [comment]
Dave is correct.  I noted the dependence in the description of this PR. Didn’t expect it to be put out to the web so quickly!
_________________________________
JerryG2003@aol.com


On Feb 26, 2021, at 3:06 PM, Dave Sand <notifications@github.com> wrote:

﻿
@jerryg2003 Where do you find a page with this sidebar? I'm trying to find it, but fails.

The sidebar is on the main page.


However, there is a timing issue. The new link points to the help tree which has not been updated yet. Those changes are in PR #9451.

I think the risk of someone using the new link is very small.

**Comment by danielb987** [comment]
For the JMRI/JMRI repository, we have to wait for the 4.22 release to come out before we can merge new PRs. And we have a rule that all PRs should wait at least 24 hours before merge so that other people have time to do the review.

For JMRI/website, that's not the case.

But I don't think it will be a problem. I was just curious about this   :-)

**Pull request merged**
