### PR TITLE
Update Sidebar.shtml

### PR DESCRIPTION
**Pull request by jerryg2003**
Make links absolute to eliminate “broken links” when referenced by acknowledgements page and any others that use it.  See issue #432.   Also PR # 9960 in JMRI/JMRI which will be withdrawn if this PR is approved.

### CODE REVIEW

**Comment by danielb987** [comment]
@dsand47 
Is this a PR that should be merged?

**Comment by dsand47** [comment]
> @dsand47
> Is this a PR that should be merged?

I don't know.  #9960 was cancelled when it was superseded by #9988.  That may have also made this PR un-needed.

Maybe @jerryg2003 knows.

**Comment by jerryg2003** [comment]
If we know for sure that no pages in either repository include /Sidebar.shtml, then this is unnecessary (in fact, /Sidebar.shtml should then be deleted).  If not, then this PR should be merged.  Thanks.

**Comment by dsand47** [comment]
> If we know for sure that no pages in either repository include /Sidebar.shtml, then this is unnecessary (in fact, /Sidebar.shtml should then be deleted). If not, then this PR should be merged. Thanks.

The **website** template specifies /`Sidebar.shtml`.  The **help** template specifies `Sidebar.shtml` (no slash).

**Comment by bobjacobsen** [comment]
This has been around for a while. Should it be merged?

**Comment by dsand47** [comment]
> This has been around for a while. Should it be merged?

I believe this is no longer needed.  PR #9988 provided an alternate solution.

**Comment by bobjacobsen** [comment]
Closed, see above.

**Pull request closed without merging**
