### PR TITLE
Update release notes for Logix issue

### PR DESCRIPTION
**Pull request by dsand47**

### CODE REVIEW

**Review by danielb987 — APPROVED** [review]
Looks good. jmri4.21.5.shtml is not updated, but that's maybe not needed?

**Comment by dsand47** [comment]
> Looks good. jmri4.21.5.shtml is not updated, but that's maybe not needed?

I don't expect anyone to be doing a new download of 4.21.5.  Production users will be moving to 4.22 and test users to 4.23.x.

**Comment by dsand47** [comment]
Does something need to be done on the web server?  I am not seeing a change on the release notes.

**Comment by danielb987** [comment]
It takes some time before the web server is updated. Maybe a couple of hours?

**Comment by dsand47** [comment]
The web pages have been updated.

I am going to post a note on the user group.

**Pull request merged**
