### PR TITLE
Add MRC 1750 (Walthers GP15-1 HO), updated MRC 1825 (Athearn SD45/60 HO)

### PR DESCRIPTION
**Pull request by AlanUS**

### CODE REVIEW

**Comment by rhwood** [comment]
JMRI/JMRI#1140 is already in the release notes. Please update your working copy and rework the release notes from that if needed.

**Comment by AlanUS** [comment]
@rhwood 
I prepared the Release Note update in parallel to JMRI/JMRI#1140. You may have missed it, as you updated the RN when merging the change. What is best: leave it to the person performing the merge to update the RN or prepare the RN change as well?

**Comment by rhwood** [comment]
Release Notes (and Release Notes only) should be directly edited in the GitHub website (or pushed from your git repo) without using a PR (assuming you have permissions to do so) because the Release Notes simply change too often to use the PR process for them. I believe this was discussed on the JMRI-developers mailing list.

Randall Wood
Alexandria Software
randall.h.wood@alexandriasoftware.com
http://alexandriasoftware.com

**Comment by AlanUS** [comment]
OK, missed that on the Developers' list. I don't think that I have been granted direct change access in the repository, so I'll indicate the changes for the RN in the comments of JMRI PR, if needed.
I close this PR and revert to HEAD.

**Pull request closed without merging**
