### PR TITLE
Add an initial "http://jmri.org/java" page

### PR DESCRIPTION
**Pull request by bobjacobsen**

### CODE REVIEW

**Comment by danielb987** [comment]
Thank you!

**Comment by jerryg2003** [comment]
Just noticed that we now have a "java" subdirectory in both the website and JMRI repositories.  Does this present any potential conflict?  Should this page perhaps be in JMRI/JMRI under help/en/html/setup?

**Comment by danielb987** [comment]
> Just noticed that we now have a "java" subdirectory in both the website and JMRI repositories. Does this present any potential conflict? Should this page perhaps be in JMRI/JMRI under help/en/html/setup?

The contents of the `java` folder in the https://github.com/JMRI/JMRI is not uploaded to the web server. So there is no conflict with the `java` folder in the https://github.com/JMRI/website repository.

**Comment by jerryg2003** [comment]
Thanks.  Didn’t know that about the two different java folders.  All sounds good.

**Pull request merged**
