### PR TITLE
Bug was introduced after 4.9.1 by Paul Bender, never released to users.

### PR DESCRIPTION
**Pull request by DanielBoudreau**

### CODE REVIEW

**Comment by pabender** [comment]
Dan,

Out of curiosity how did you decide that I made a change that introduced the bug you're talking about here?

I'm trying to find the change I made you are referring to, but I can't find a change that I made to any of the operations code since 4.9.1 was released (and the last change I can find that I made to CarManagerXml.java was in February, and I think that's the file you're talking about...)

Paul

**Comment by DanielBoudreau** [comment]
Sorry, it looks like the code change was made by Randall, not you.

**Comment by rhwood** [comment]
If we are going to be calling each other out like this, we need to be:
1. specific about what we did - I don't know what I did from this or other communications
2. calling out changes that users will see or be affected by - You make the claim that what I broke and you fixed was between the releases of 4.9.1 and 4.9.2, but seem to feel the need to include it in the release notes that someone broke something and you fixed it. Irrespective of who broke something like this, this name calling should be removed from the release notes.

**Comment by pabender** [comment]
> On Aug 18, 2017, at 6:22 AM, Randall Wood <notifications@github.com> wrote:
> Irrespective of who broke something like this, this name calling should be removed from the release notes.

Agreed, name calling should NEVER be in the release notes or ( in this case ) a commit message.

The fact is it doesn't matter who introduced a bug.  We all introduce bugs at some point in time, we are all humans after all.

Even if you can find the commit that "introduced" a bug, using 'git bisect' or some other means, all you can really say is that a given commit triggered the bug.  The actual bug may have been introduced by the commit that triggered it, but it could have been introduced months or years before.

Paul

**Pull request merged**
