### PR TITLE
Home page image

### PR DESCRIPTION
**Pull request by silverailscolo**
Proposal for a photograph of person on JMRI home page (for careful, broad consideration)

### CODE REVIEW

**Comment by silverailscolo** [comment]
Wouldn’t it be nice to give the JMRI starting page more of a human touch? Many of the pages deal with lines and lines of text, lists etc. so another drawing of digital signals or control levers is still too factual, I think. I’ve been looking for a public domain image that shows people, either running trains; even better smiling, but alas. I came across this image of a fireman looking out of the cab windows (I mirrored it to have him look towards the user; someone will certainly spot this). It should’t take up too much space on the home page, so I suggest to add this or any better image, fading to white to the left and a bit fainted and adjusted to the color scheme of the site, to the right of the first text block. If merged, it would at first be a copy of index.shtml to view before replacing.

**Comment by bobjacobsen** [comment]
Here's what it looks like on Mac Safari. I've crunched the window down a bit from my typical size to make a more reasonable image size.

cursor_and_jmri__a_java_model_railroad_interface_and_jmri_site_local_ _tcsh_ _ 1

The pensive look is kind of a neat effect.  Calming.  Better than somebody pulling their hair out over some problem they're having....

**Comment by mattharris** [comment]
I like this proposal.

**Comment by Walter71342JMRI** [comment]
How about a female RR worker.
might encourage people that think this is to hard.
Walt

**Comment by silverailscolo** [comment]
Thanks for your responses.
As I was searching for a picture, I didn’t find any women portrayed, let alone in public domain/creative commons license. And then I thought: if model railroaders in general are 80% above 40, we can’t be blamed for misrepresenting the user base. (AP reported in 2007, the average age of model railroaders had been going up. It was 30 in the 1970s, 40 in the ’80s, 50 in the ’90s, and presumably is even higher now.)

@Walter, have you got an image available? I’m sure that was meant as a joke (“women" & “difficult").
You’re totally right about a woman or a younger male working the trains using JMRI is a real use case.

Or some happy "Travel by Rail" ad from the 1950s might replace picture #1 after a couple of months. This one isn’t very inspiring:
https://groups.yahoo.com/neo/groups/DRGW/photos/photostream/lightbox/421445089#zax/421445089

Egbert

**Comment by walter** [comment]
I think you meant to mention another Walter, rather than me. Unsubscribing...

**Comment by rhwood** [comment]
Given the commenter's stated intent of using a woman to show how easy JMRI is to use, I strongly suggest using a woman not be pursued.

**Comment by Walter71342JMRI** [comment]
"Tongue is Cheek" that a picture of a woman RR worker, was in bad taste and
I apologize.

Trying to show, some how, that JMRI can be easy to use could help.

Maybe a picture of a younger person operating a model?

Walt

**Comment by silverailscolo** [comment]
Are we ready for this refreshing change?

**Comment by bobjacobsen** [comment]
> Are we ready for this refreshing change?

I like the version with the image you first proposed.

Bob

**Comment by rhwood** [comment]
👍

**Comment by Walter71342JMRI** [comment]
GO

**Pull request merged**
