### PR TITLE
Add instructions for local JRE

### PR DESCRIPTION
**Pull request by bobjacobsen**
The corresponding code is in JMRI/JMRI#10999

### CODE REVIEW

**Review by dsand47 — CHANGES_REQUESTED** [review]
There are a number of tidy warnings, especially h2 tags with a closing h3.
```
das@dmba java % tidy -e index.shtml
line 37 column 41 - Warning: <a> discarding newline in URI reference
line 37 column 41 - Warning: <a> discarding whitespace in URI reference
line 37 column 41 - Warning: <a> discarding whitespace in URI reference
line 37 column 41 - Warning: <a> discarding whitespace in URI reference
line 37 column 41 - Warning: <a> discarding whitespace in URI reference
line 37 column 41 - Warning: <a> discarding whitespace in URI reference
line 37 column 41 - Warning: <a> discarding whitespace in URI reference
line 37 column 41 - Warning: <a> discarding whitespace in URI reference
line 48 column 1 - Warning: missing </h2> before </h3>
line 48 column 36 - Warning: discarding unexpected </h3>
line 51 column 69 - Warning: unescaped & or unknown entity "&package"
line 76 column 101 - Warning: unescaped & or unknown entity "&field_operating_system_target_id"
line 76 column 138 - Warning: unescaped & or unknown entity "&field_architecture_target_id"
line 76 column 171 - Warning: unescaped & or unknown entity "&field_java_package_target_id"
line 75 column 5 - Info: missing optional end tag </li>
line 83 column 5 - Info: missing optional end tag </li>
line 96 column 1 - Warning: missing </h2> before </h3>
line 96 column 26 - Warning: discarding unexpected </h3>
line 97 column 1 - Warning: missing </span> before <a>
line 95 column 1 - Warning: missing </a> before <a>
line 97 column 69 - Warning: discarding unexpected </span>
line 110 column 9 - Info: missing optional end tag </li>
line 111 column 9 - Info: missing optional end tag </li>
line 112 column 9 - Info: missing optional end tag </li>
line 114 column 9 - Info: missing optional end tag </li>
line 115 column 37 - Warning: <img> attribute with missing trailing quote mark
line 115 column 9 - Info: missing optional end tag </li>
line 126 column 9 - Info: missing optional end tag </li>
line 127 column 43 - Warning: <img> attribute with missing trailing quote mark
line 128 column 79 - Warning: unescaped & or unknown entity "&package"
line 127 column 9 - Info: missing optional end tag </li>
line 130 column 9 - Info: missing optional end tag </li>
line 131 column 9 - Info: missing optional end tag </li>
line 132 column 9 - Info: missing optional end tag </li>
line 134 column 9 - Info: missing optional end tag </li>
line 135 column 9 - Info: missing optional end tag </li>
Info: Document content looks like HTML5
Tidy found 22 warnings and 0 errors!
```

**Comment by bobjacobsen** [comment]
Thanks.  Got it down to
```
line 50 column 69 - Warning: unescaped & or unknown entity "&package"
line 75 column 101 - Warning: unescaped & or unknown entity "&field_operating_system_target_id"
line 75 column 138 - Warning: unescaped & or unknown entity "&field_architecture_target_id"
line 75 column 171 - Warning: unescaped & or unknown entity "&field_java_package_target_id"
line 127 column 79 - Warning: unescaped & or unknown entity "&package"
```

But these are required ampersands in quoted URLs.  Is it correct to change them to `&amp;`?

**Comment by dsand47** [comment]
> Thanks. Got it down to
> 
> ```
> line 50 column 69 - Warning: unescaped & or unknown entity "&package"
> line 75 column 101 - Warning: unescaped & or unknown entity "&field_operating_system_target_id"
> line 75 column 138 - Warning: unescaped & or unknown entity "&field_architecture_target_id"
> line 75 column 171 - Warning: unescaped & or unknown entity "&field_java_package_target_id"
> line 127 column 79 - Warning: unescaped & or unknown entity "&package"
> ```
> 
> But these are required ampersands in quoted URLs. Is it correct to change them to `&amp;`?

At least in Safari, changing them to `&amp;` works.

**Comment by bobjacobsen** [comment]
Found a standard reference that talks about using `&amp;`: https://www.w3.org/TR/html401/appendix/notes.html#non-ascii-chars

**Comment by dsand47** [comment]
The `since` span does not work with the embedded anchor.  It also probably should by 4.99.9.  I tend to put since tags within a h? tag.

Screen Shot 2022-05-17 at 1 29 49 PM

The link itself is not valid.

**Comment by bobjacobsen** [comment]
Sorry, don't understand.
This is the format for all the `@since` links in the release notes:
```
<span class="since">Since <a href="jmri4.99.1.shtml">JMRI 4.99.1</a></span>
```
See for example https://www.jmri.org/releasenotes/jmri4.99.8.shtml

What would be different about this page doing that same thing, other than the URL needing fixing?

**Comment by dsand47** [comment]
The `since` problem is caused by:
```
<a id="local"/>
<h2>Local install option:</h2>
```

The a tag apparently needs `<a..></a>`.

The easy fix:
`<h2 id="local">Local install option:</h2>`

**Review by dsand47 — APPROVED** [review]

**Pull request merged**
