### PR TITLE
Create jmri4.5.6.shtml

### PR DESCRIPTION
**Pull request by crosland**
Added custom scale selection at request of Bachrus

### CODE REVIEW

**Comment by bobjacobsen** [comment]
Did you intend for this to be in 4.7.6?

**Comment by crosland** [comment]
I have submitted a fix for the failing .properties.

I would like it to be in 4.8 if possible. 4.7.6 or 4.7.7 is fine.

Andrew

------ Original Message ------

**Comment by crosland** [comment]
Sorry, I completely missed tho point of your question. Yes, it should be 
4.7.6, not 4.5.6.

------ Original Message ------

**Comment by bobjacobsen** [comment]
OK, thanks.  Will merge the change into both, and update release notes. (Will probably be tomorrow, working from phone today)

**Comment by bobjacobsen** [comment]
See #231

**Pull request closed without merging**
