### PR TITLE
4.1.4 notes for DCC++

### PR DESCRIPTION
**Pull request by msunderwd**
Updated 4.1.4 release notes with recent updates for DCC++

### CODE REVIEW

**Comment by rhwood** [comment]
Are these intended to be updates to the notes for the already released 4.1.4 or are they intended for the next release?

**Comment by msunderwd** [comment]
4.1.4 is already out?

Yes these are updates for the 4.1.4 release notes.

**Comment by bobjacobsen** [comment]
> 4.1.1 is already out?

Yes, on November 25th.  Next up is 4.1.5 sometime this weekend (likely), which is the last "all new features" release before 4.2 in a couple weeks.  The run-up to 4.2 schedule was proposed in a [jmri-developers email](https://sourceforge.net/p/jmri/mailman/message/34646246/).

**Comment by msunderwd** [comment]
Oh. OK. Then yeah, that stuff should be fore the 4.1.5 release.  Just kill
the PR and I'll go edit the 4.1.5 release notes.  Sorry. I thought 4.1.4
was still being held up by the preferences issue.

**Comment by rhwood** [comment]
Closing per request.

**Comment by msunderwd** [comment]
Follow-up question on the schedule... IIRC, traditionally the next
developer release is dropped right after or the same time as a production
release... will 4.3.1 be coming out at the same time as 4.2.0, or later
(e.g. January)?

- Mark

**Pull request closed without merging**
